version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8080
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8080
      - KEYCLOAK_URL=http://keycloak:8080
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3001:3000"
    depends_on:
      - backend
      - keycloak

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://user:password@maxscale/dbname
      - KEYCLOAK_URL=http://keycloak:8080
    ports:
      - "8080:8080"
    depends_on:
      - maxscale
      - keycloak

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql://user:password@maxscale/dbname
      - KEYCLOAK_URL=http://keycloak:8080
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8081:8080"
    depends_on:
      - maxscale
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=mysql
      - DB_ADDR=maxscale
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8080:8080"
    depends_on:
      - maxscale

  maxscale:
    image: mariadb/maxscale
    ports:
      - "3306:3306"
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
    depends_on:
      - db1
      - db2

  db1:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db1_data:/var/lib/mysql
      - ./db1.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld
    ports:
      - "3307:3306"

  db2:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - db2_data:/var/lib/mysql
      - ./db2.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld
    ports:
      - "3308:3306"

volumes:
  db1_data:
  db2_data:
